In [1]:
import pricer
import numpy as np
import pandas as pd

In [2]:
help(pricer)

Help on module pricer:

NAME
    pricer

CLASSES
    builtins.object
        monte_carlo_simulator
    
    class monte_carlo_simulator(builtins.object)
     |  monte_carlo_simulator(model_params, cur_mkt_val, maturity, sim_info)
     |  
     |  Methods defined here:
     |  
     |  __init__(self, model_params, cur_mkt_val, maturity, sim_info)
     |      model_params: theta (array of func of t, days. [theta_e, theta_g]), rho, alpha(array of size 2, [alpha_e, alpha_g]), vol, win_len
     |      cur_mkt_val: e0, g0
     |      maturity: T
     |      sim_info: num_sim, n_steps
     |  
     |  fourier_vol_sim(self)
     |  
     |  rolling_vol_sim(self)
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)

FUNCTIONS
    energy_euro_call(h

In [3]:
#from calibration import volatility

In [4]:
model_params = [np.array([lambda x: 0.1, lambda x: 0.2]), 0.9, np.array([5.2, 4.4]), None, 20]
cur_mkt_val = [82/20, 9.52]
maturity = 1 
sim_info = [1000, 240]
model = pricer.monte_carlo_simulator(model_params, cur_mkt_val, maturity, sim_info)

In [5]:
history = model.rolling_vol_sim()

In [6]:
pricer.energy_futures(history)

(array([70.23781112, 46.04209435, 30.46112784, 20.42565625, 13.92230519,
         9.71235263,  7.00042428,  5.26378386,  4.13892135,  3.41343442,
         2.94607305,  2.64540293]),
 array([168.13154718, 117.16185638,  81.88480264,  58.05689174,
         41.42856361,  29.88296077,  21.90131659,  16.42710849,
         12.63471305,  10.01492409,   8.21183775,   6.96713149]))

In [8]:
pricer.energy_euro_call(history, [0.1, 3], pricer.yield_curve, 1)

(array([2.57567173, 1.65801989, 1.06586792, 0.6875234 , 0.44232843,
        0.28374258, 0.18236245, 0.11739619, 0.07541955, 0.04843608,
        0.0311151 , 0.02000773]),
 array([3.64242843, 1.64408143, 0.42826258, 0.01814768, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]))